/**
 * Full v0.2-style offensive + defensive catalog.
 * POC HTML not in repo — ids, types, and powers follow docs/game/GAME_DESIGN.md.
 * Rarity from Locker Room Track A examples + starter attribution for opening-deck cards.
 */

import type { SeedCard } from './types';

/** Slugs tagged `starter` ship in the default starter deck; others are draft-pool rarities. */
export const STARTER_CARDS: SeedCard[] = [
  /* -------- Offense — run-in -------- */
  {
    _id: 'hb-dive',
    side: 'offense',
    type: 'run-in',
    name: 'HB Dive',
    basePower: 5,
    notes: 'Reliable; beats zone hard.',
    rarity: 'starter',
    isActive: true,
  },
  {
    _id: 'fb-smash',
    side: 'offense',
    type: 'run-in',
    name: 'FB Smash',
    basePower: 6,
    notes: 'North-south push.',
    rarity: 'common',
    draftCost: 1,
    isActive: true,
  },
  {
    _id: 'draw-play',
    side: 'offense',
    type: 'run-in',
    name: 'Draw Play',
    basePower: 7,
    notes: 'Late handoff; punishes aggressive fronts.',
    rarity: 'starter',
    isActive: true,
  },
  /* -------- Offense — run-out -------- */
  {
    _id: 'sweep-right',
    side: 'offense',
    type: 'run-out',
    name: 'Sweep Right',
    basePower: 5,
    notes: 'Higher upside; punished by Run D.',
    rarity: 'starter',
    isActive: true,
  },
  {
    _id: 'stretch-run',
    side: 'offense',
    type: 'run-out',
    name: 'Stretch Run',
    basePower: 5,
    notes: 'Edge attack; spacing vs. linebackers.',
    rarity: 'common',
    draftCost: 1,
    isActive: true,
  },
  /* -------- Offense — pass-s -------- */
  {
    _id: 'slant-route',
    side: 'offense',
    type: 'pass-s',
    name: 'Slant Route',
    basePower: 5,
    notes: 'Beats blitz; weak vs. man.',
    rarity: 'starter',
    isActive: true,
  },
  {
    _id: 'screen-pass',
    side: 'offense',
    type: 'pass-s',
    name: 'Screen Pass',
    basePower: 5,
    notes: 'Screen behind pressure.',
    rarity: 'starter',
    isActive: true,
  },
  {
    _id: 'curl-route',
    side: 'offense',
    type: 'pass-s',
    name: 'Curl Route',
    basePower: 5,
    notes: 'Sit beyond linebackers.',
    rarity: 'common',
    draftCost: 1,
    isActive: true,
  },
  /* -------- Offense — pass-m -------- */
  {
    _id: 'cross-route',
    side: 'offense',
    type: 'pass-m',
    name: 'Cross Route',
    basePower: 7,
    notes: 'Balanced; beats stacked box.',
    rarity: 'uncommon',
    draftCost: 2,
    isActive: true,
  },
  {
    _id: 'dig-route',
    side: 'offense',
    type: 'pass-m',
    name: 'Dig Route',
    basePower: 7,
    notes: 'Intermediate timing.',
    rarity: 'uncommon',
    draftCost: 2,
    isActive: true,
  },
  /* -------- Offense — pass-d -------- */
  {
    _id: 'post-route',
    side: 'offense',
    type: 'pass-d',
    name: 'Post Route',
    basePower: 8,
    notes: 'High ceiling; INT risk on big losses.',
    rarity: 'uncommon',
    draftCost: 2,
    isActive: true,
  },
  {
    _id: 'deep-ball',
    side: 'offense',
    type: 'pass-d',
    name: 'Deep Ball',
    basePower: 9,
    notes: 'Shot play; volatility.',
    rarity: 'rare',
    draftCost: 3,
    isActive: true,
  },
  /* -------- Offense — option -------- */
  {
    _id: 'read-option',
    side: 'offense',
    type: 'option',
    name: 'Read Option',
    basePower: 7,
    notes: '±3 chaos modifier on resolve.',
    rarity: 'starter',
    isActive: true,
  },
  {
    _id: 'flea-flicker',
    side: 'offense',
    type: 'option',
    name: 'Flea Flicker',
    basePower: 8,
    notes: 'Trick shot; sell the run first.',
    rarity: 'rare',
    draftCost: 3,
    isActive: true,
  },
  /* -------- Offense — rogue -------- */
  {
    _id: 'hail-mary',
    side: 'offense',
    type: 'rogue',
    name: 'Hail Mary',
    basePower: 0,
    notes: 'Coin flip on snap: power becomes 20 or 0.',
    rarity: 'rare',
    draftCost: 3,
    isActive: true,
  },
  {
    _id: 'film-study',
    side: 'offense',
    type: 'rogue',
    name: 'Film Study',
    basePower: 0,
    notes: "Reveals the CPU's defense card for this play at no power cost.",
    rarity: 'legendary',
    draftCost: 5,
    isActive: true,
  },
  /* -------- Defense — run-d -------- */
  {
    _id: 'stack-the-box',
    side: 'defense',
    type: 'run-d',
    name: 'Stack the Box',
    basePower: 6,
    notes: 'Crushes runs; exposed to pass.',
    rarity: 'starter',
    isActive: true,
  },
  {
    _id: 'gap-shoot',
    side: 'defense',
    type: 'run-d',
    name: 'Gap Shoot',
    basePower: 7,
    notes: 'One-gap aggression.',
    rarity: 'common',
    draftCost: 1,
    isActive: true,
  },
  {
    _id: 'lb-blitz',
    side: 'defense',
    type: 'run-d',
    name: 'LB Blitz',
    basePower: 8,
    notes: 'Run-fit blitz from the second level.',
    rarity: 'rare',
    draftCost: 3,
    isActive: true,
  },
  /* -------- Defense — zone -------- */
  {
    _id: 'cover-2',
    side: 'defense',
    type: 'zone',
    name: 'Cover 2',
    basePower: 5,
    notes: 'Limits deep ball; screen-vulnerable.',
    rarity: 'starter',
    isActive: true,
  },
  {
    _id: 'cover-3',
    side: 'defense',
    type: 'zone',
    name: 'Cover 3',
    basePower: 6,
    notes: 'Shell coverage; flats tighter than 2.',
    rarity: 'common',
    draftCost: 1,
    isActive: true,
  },
  /* -------- Defense — man -------- */
  {
    _id: 'press-man',
    side: 'defense',
    type: 'man',
    name: 'Press Man',
    basePower: 6,
    notes: 'Shuts short; big-play risk.',
    rarity: 'starter',
    isActive: true,
  },
  {
    _id: 'bump-and-run',
    side: 'defense',
    type: 'man',
    name: 'Bump & Run',
    basePower: 7,
    notes: 'Physical at the line.',
    rarity: 'common',
    draftCost: 1,
    isActive: true,
  },
  /* -------- Defense — blitz -------- */
  {
    _id: 'safety-blitz',
    side: 'defense',
    type: 'blitz',
    name: 'Safety Blitz',
    basePower: 7,
    notes: 'Disrupts everything; countered by screen.',
    rarity: 'uncommon',
    draftCost: 2,
    isActive: true,
  },
  {
    _id: 'db-blitz',
    side: 'defense',
    type: 'blitz',
    name: 'DB Blitz',
    basePower: 8,
    notes: 'Corner or nickel heat.',
    rarity: 'uncommon',
    draftCost: 2,
    isActive: true,
  },
  {
    _id: 'prevent-d',
    side: 'defense',
    type: 'prevent',
    name: 'Prevent D',
    basePower: 4,
    notes: 'Low risk; situational late game.',
    rarity: 'common',
    draftCost: 1,
    isActive: true,
  },
];
