import type { SeedPlaymaker } from './types';

/** Opening five per side (GAME_DESIGN starter table). */
export const STARTER_PLAYMAKERS: SeedPlaymaker[] = [
  {
    _id: 'pm-qb-sterling',
    side: 'offense',
    position: 'QB',
    name: 'D. Sterling',
    baseBoost: 1.5,
    affinityTypes: ['pass-s', 'pass-m', 'pass-d', 'rogue'],
    rarity: 'starter',
    isActive: true,
  },
  {
    _id: 'pm-rb-cannon',
    side: 'offense',
    position: 'RB',
    name: 'J. Cannon',
    baseBoost: 1.4,
    affinityTypes: ['run-in', 'run-out'],
    rarity: 'starter',
    isActive: true,
  },
  {
    _id: 'pm-wr-flash',
    side: 'offense',
    position: 'WR',
    name: 'T. Flash',
    baseBoost: 1.3,
    affinityTypes: ['pass-s', 'pass-m', 'pass-d', 'option'],
    rarity: 'starter',
    isActive: true,
  },
  {
    _id: 'pm-te-anchor',
    side: 'offense',
    position: 'TE',
    name: 'M. Anchor',
    baseBoost: 1.25,
    affinityTypes: ['pass-s', 'pass-m', 'run-in', 'option'],
    rarity: 'starter',
    isActive: true,
  },
  {
    _id: 'pm-ol-wall',
    side: 'offense',
    position: 'OL',
    name: 'B. Wall',
    baseBoost: 1.2,
    affinityTypes: ['run-in'],
    rarity: 'starter',
    specialEffect: 'sack-risk-removed-run-in',
    isActive: true,
  },
  {
    _id: 'pm-dt-mountain',
    side: 'defense',
    position: 'DT',
    name: 'R. Mountain',
    baseBoost: 1.4,
    affinityTypes: ['run-d'],
    rarity: 'starter',
    isActive: true,
  },
  {
    _id: 'pm-lb-hammer',
    side: 'defense',
    position: 'LB',
    name: 'K. Hammer',
    baseBoost: 1.35,
    affinityTypes: ['run-d', 'blitz'],
    rarity: 'starter',
    isActive: true,
  },
  {
    _id: 'pm-cb-shadow',
    side: 'defense',
    position: 'CB',
    name: 'D. Shadow',
    baseBoost: 1.4,
    affinityTypes: ['man'],
    rarity: 'starter',
    isActive: true,
  },
  {
    _id: 'pm-s-rover',
    side: 'defense',
    position: 'S',
    name: 'L. Rover',
    baseBoost: 1.3,
    affinityTypes: ['zone', 'blitz'],
    rarity: 'starter',
    isActive: true,
  },
  {
    _id: 'pm-de-edge',
    side: 'defense',
    position: 'DE',
    name: 'T. Edge',
    baseBoost: 1.35,
    affinityTypes: ['blitz', 'run-d'],
    rarity: 'starter',
    isActive: true,
  },
];

/** Track C recruit pool (GAME_DESIGN). */
export const RECRUIT_PLAYMAKERS: SeedPlaymaker[] = [
  {
    _id: 'pm-eqb-knight',
    side: 'offense',
    position: 'eQB',
    name: 'E. Knight',
    baseBoost: 1.6,
    affinityTypes: ['pass-s', 'pass-m', 'pass-d'],
    rarity: 'recruit-rare',
    recruitCost: 4,
    specialEffect: 'pre-snap-peek',
    isActive: true,
  },
  {
    _id: 'pm-srb-rocket',
    side: 'offense',
    position: 'sRB',
    name: 'B. Rocket',
    baseBoost: 1.55,
    affinityTypes: ['run-in', 'run-out'],
    rarity: 'recruit-uncommon',
    recruitCost: 3,
    specialEffect: 'breaks-tackles',
    isActive: true,
  },
  {
    _id: 'pm-swr-blaze',
    side: 'offense',
    position: 'sWR',
    name: 'C. Blaze',
    baseBoost: 1.45,
    affinityTypes: ['pass-s'],
    rarity: 'recruit-uncommon',
    recruitCost: 3,
    specialEffect: 'auto-plus2-vs-blitz',
    isActive: true,
  },
  {
    _id: 'pm-mlb-stone',
    side: 'defense',
    position: 'MLB',
    name: 'T. Stone',
    baseBoost: 1.5,
    affinityTypes: ['run-d'],
    rarity: 'recruit-uncommon',
    recruitCost: 3,
    specialEffect: 'stuffs-carries',
    isActive: true,
  },
  {
    _id: 'pm-fs-banks',
    side: 'defense',
    position: 'FS',
    name: 'R. Banks',
    baseBoost: 1.45,
    affinityTypes: ['zone'],
    rarity: 'recruit-uncommon',
    recruitCost: 3,
    specialEffect: 'int-on-deep-losses',
    isActive: true,
  },
  {
    _id: 'pm-scb-lock',
    side: 'defense',
    position: 'sCB',
    name: 'J. Lock',
    baseBoost: 1.5,
    affinityTypes: ['man'],
    rarity: 'recruit-rare',
    recruitCost: 4,
    specialEffect: 'nullify-top-wr',
    isActive: true,
  },
  {
    _id: 'pm-olb-wreck',
    side: 'defense',
    position: 'OLB',
    name: 'D. Wreck',
    baseBoost: 1.5,
    affinityTypes: ['blitz', 'run-d'],
    rarity: 'recruit-rare',
    recruitCost: 4,
    specialEffect: 'fumble-on-tfl',
    isActive: true,
  },
];

export const ALL_SEED_PLAYMAKERS: SeedPlaymaker[] = [...STARTER_PLAYMAKERS, ...RECRUIT_PLAYMAKERS];
